import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "gr";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Initial translations structure
export const translations: Record<Language, Record<string, string>> = {
  en: {
    "nav.home": "Home",
    "nav.websites": "Websites",
    "nav.growth": "Growth",
    "nav.ai_lab": "AI Lab",
    "nav.services": "Services",
    "nav.studio": "Studio",
    "nav.portfolio": "Portfolio",
    "nav.ecosystem": "Ecosystem",
    "nav.academy": "Academy",
    "nav.space": "Space",
    "nav.brief": "Build a Project",
    "hero.badge": "Startup Studio . Digital Agency . Private Hub",
    "hero.title1": "We don't build websites.",
    "hero.title2": "We build businesses.",
    "hero.subtitle1": "Some we build for clients.",
    "hero.subtitle2": "Some we build with.",
    "hero.cta1": "Build my project",
    "hero.cta2": "Pitch your idea",
    "hero.locations": "Athens . London . Dubai",
    "intro.badge": "The Lab Identity",
    "intro.title1": "More than an Agency.",
    "intro.title2": "More than a Space.",
    "intro.title3": "A hub for Builders.",
    "intro.text1": "HustleLabs is where ideas become real.",
    "intro.text2": "We combine strategy, technology and execution to turn concepts into something that actually works.",
    "forBusinesses.badge": "FOR BUSINESSES",
    "forBusinesses.title": "Build\nfor you",
    "forBusinesses.subtitle": "You bring the business. We build the engine.",
    "forBusinesses.text": "We create high-performance websites, systems and marketing strategies for businesses that want to grow fast and properly.",
    "forBusinesses.cta": "Start a project",
    "forFounders.badge": "FOR FOUNDERS",
    "forFounders.title": "Build\nwith you",
    "forFounders.subtitle": "You bring the idea. We build it together.",
    "forFounders.text1": "Some ideas need more than a service. They need a partner.",
    "forFounders.text2": "In selected cases, we collaborate, build and grow projects together.",
    "forFounders.cta": "Pitch your idea",
    "roster.badge": "Selected Works",
    "roster.title1": "Building",
    "roster.title2": "Digital Excellence.",
    "roster.subtitle1": "Not just projects. High-performance builds.",
    "roster.subtitle2": "A curated selection of case studies that prove our ability to turn vision into profitable reality.",
    "growth.badge": "Scale your vision",
    "growth.title1": "Growth",
    "growth.title2": "Systems",
    "growth.subtitle": "Transparent pricing for projects that want to disrupt the status quo.",
    "growth.starter.name": "The Starter",
    "growth.starter.price": "from €1.8k",
    "growth.starter.desc": "High-end corporate presence for businesses that deserve a premium digital identity.",
    "growth.scale.name": "The Scale",
    "growth.scale.price": "Custom",
    "growth.scale.desc": "Full automated systems, custom dashboards and growth engines for high-scale operations.",
    "growth.fractional.name": "The Fractional",
    "growth.fractional.price": "Monthly",
    "growth.fractional.desc": "Your own CTO and Creative Director as a service. Continuous development and strategy.",
    "growth.cta": "Request Access",
    "growth.badge_most_efficient": "Most Efficient",
    "space.badge": "Physical HQ",
    "space.title": "Hustle\nSpace",
    "space.text": "Our premium hybrid hub in Chania. Co-working, networking and experimentation for restless minds.",
    "portfolio.hero.badge": "The Archive · Strategy · Execution",
    "portfolio.hero.title1": "Real Projects.",
    "portfolio.hero.title2": "Built to scale.",
    "portfolio.hero.subtitle1": "We don't build just websites.",
    "portfolio.hero.subtitle2": "We build high-performance digital engines.",
    "portfolio.hero.explore": "Explore Deployments",
    "portfolio.hero.start": "Start Your Project",
    "portfolio.featured.badge": "High Impact",
    "portfolio.featured.title1": "Selected",
    "portfolio.featured.title2": "Works.",
    "portfolio.featured.subtitle": "Case studies that prove the ROI.",
    "portfolio.archive.badge": "The Archive",
    "portfolio.archive.title1": "All",
    "portfolio.archive.title2": "Builds.",
    "portfolio.archive.empty": "No deployments found in this sector.",
    "portfolio.cta.badge": "THE EXECUTION PARTNER",
    "portfolio.cta.title1": "Build the",
    "portfolio.cta.title2": "Future.",
    "portfolio.cta.subtitle": "Strategy and execution for brands that demand the absolute best.",
    "portfolio.cta.button": "Start Your Project",
    "portfolio.investments.badge": "Investment Arm",
    "portfolio.investments.title": "Hustle Backed Projects",
    "portfolio.investments.subtitle": "Projects and ideas of others where Hustle invests capital, technology, and strategic guidance.",
    "footer.rights": "All rights reserved.",
    "ecosystem.hero.badge": "The Infinite Ecosystem",
    "ecosystem.hero.title1": "Everything you need",
    "ecosystem.hero.title2": "to build & grow.",
    "ecosystem.hero.subtitle": "From professional services to strategic backing. We built an ecosystem for the next generation of builders.",
    "ecosystem.hero.cta1": "Start Your Journey",
    "ecosystem.hero.cta2": "Start a Project",
    "ecosystem.structure.badge": "Structure",
    "ecosystem.structure.title1": "We build.",
    "ecosystem.structure.title2": "We back.",
    "ecosystem.structure.title3": "We grow together.",
    "ecosystem.structure.text": "HustleLabs is a hybrid machine. We combine the execution power of a digital agency with the strategic vision of a startup studio.",
    "ecosystem.structure.agency.title": "The Agency (Build for you)",
    "ecosystem.structure.agency.desc": "High-performance tech, marketing and growth systems for businesses.",
    "ecosystem.structure.studio.title": "The Studio (Build with you)",
    "ecosystem.structure.studio.desc": "Strategic backing, product development and equity-based partnerships.",
    "ecosystem.universe.badge": "COMPONENTS",
    "ecosystem.universe.title": "The Lab Universe.",
    "ecosystem.universe.academy.title": "Hustle Academy",
    "ecosystem.universe.academy.desc": "Where students & founders find the real-world knowledge to build businesses without corporate fluff.",
    "ecosystem.universe.space.title": "Hustle Space",
    "ecosystem.universe.space.desc": "Our premium hybrid hub in Chania. Co-working, networking and experimentation for restless minds.",
    "ecosystem.universe.studio.title": "Hustle Studio",
    "ecosystem.universe.studio.desc": "Professional podcasts, vidcasts and content creation equipment for visionaries who want to be heard.",
    "ecosystem.universe.network.title": "Hustle Network",
    "ecosystem.universe.network.desc": "A curated ecosystem of founders, creators and experts supporting each other and building together.",
    "ecosystem.universe.explore": "Explore",
    "ecosystem.universe.soon": "Coming Soon",
    "ecosystem.network.badge": "Network",
    "ecosystem.network.title": "The home of",
    "ecosystem.network.title_span": "restless ideas.",
    "ecosystem.network.text": "We choose projects that are worth building. From high-growth startups to established businesses scaling their digital dominance.",
    "ecosystem.network.cta": "Explore Network",
    "ecosystem.manifesto.title": "The home of every",
    "ecosystem.manifesto.title_span": "restless mind.",
    "ecosystem.manifesto.text": "From the student taking the first step to the dreamer who just wants a space to experiment and build the future.",
    "ecosystem.final.badge": "Evolution",
    "ecosystem.final.title1": "Build the",
    "ecosystem.final.title2": "Future.",
    "ecosystem.final.cta1": "Start Now",
    "ecosystem.final.cta2": "Discovery Call",
    "ecosystem.final.quote": "\"If you are ready to evolve, we are here.\"",
    "header.tooltip.project": "Let's build something that works",
    "header.tooltip.space": "Work from our space for a day",
    "tech.badge": "The Standard Tech Stack",
    "execution.badge": "Standard of Execution",
    "execution.title1": "Hard-core Engineering.",
    "execution.title2": "Mathematical Growth.",
    "execution.step1.label": "Concept Validation",
    "execution.step1.desc": "We don't build until we prove the market gap. Precision strategy is the first line of code.",
    "execution.step2.label": "System Architecture",
    "execution.step2.desc": "Next-gen builds requiring zero maintenance. Scalable, secure, and lightning fast.",
    "execution.step3.label": "Aggressive Scaling",
    "execution.step3.desc": "Transitioning from a product to a market leader through automated growth engines.",
  },
  gr: {
    "nav.home": "Αρχική",
    "nav.websites": "Websites",
    "nav.growth": "Growth",
    "nav.ai_lab": "AI Lab",
    "nav.services": "Υπηρεσίες",
    "nav.studio": "Studio",
    "nav.portfolio": "Portfolio",
    "nav.ecosystem": "Ecosystem",
    "nav.academy": "Academy",
    "nav.space": "Space",
    "nav.brief": "Ξεκίνα Project",
    "hero.badge": "Startup Studio . Digital Agency . Private Hub",
    "hero.title1": "Δεν χτίζουμε ιστοσελίδες.",
    "hero.title2": "Χτίζουμε επιχειρήσεις.",
    "hero.subtitle1": "Άλλες τις χτίζουμε για πελάτες.",
    "hero.subtitle2": "Άλλες μαζί τους.",
    "hero.cta1": "Build my project",
    "hero.cta2": "Pitch your idea",
    "hero.locations": "Αθήνα . Λονδίνο . Ντουμπάι",
    "intro.badge": "The Lab Identity",
    "intro.title1": "Πέρα από ένα Agency.",
    "intro.title2": "Πέρα από ένα Space.",
    "intro.title3": "Μόνο για πραγματικούς Builders.",
    "intro.text1": "Το HustleLabs είναι το μέρος όπου οι ιδέες γίνονται πραγματικότητα.",
    "intro.text2": "Συνδυάζουμε στρατηγική, τεχνολογία και υλοποίηση για να μετατρέψουμε τα concepts σε κάτι που πραγματικά λειτουργεί.",
    "forBusinesses.badge": "ΓΙΑ ΕΠΙΧΕΙΡΗΣΕΙΣ",
    "forBusinesses.title": "Χτίζουμε\nγια εσάς",
    "forBusinesses.subtitle": "Εσύ φέρνεις την επιχείρηση. Εμείς χτίζουμε τη μηχανή.",
    "forBusinesses.text": "Δημιουργούμε ιστοσελίδες υψηλών επιδόσεων, συστήματα και στρατηγικές marketing για επιχειρήσεις που θέλουν να αναπτυχθούν σωστά και γρήγορα.",
    "forBusinesses.cta": "Ξεκίνα ένα project",
    "forFounders.badge": "ΓΙΑ FOUNDERS",
    "forFounders.title": "Χτίζουμε\nμαζί σας",
    "forFounders.subtitle": "Εσύ φέρνεις την ιδέα. Την χτίζουμε μαζί.",
    "forFounders.text1": "Κάποιες ιδέες χρειάζονται κάτι παραπάνω από μια υπηρεσία. Χρειάζονται έναν συνεργάτη.",
    "forFounders.text2": "Σε επιλεγμένες περιπτώσεις, συνεργαζόμαστε, χτίζουμε και αναπτύσσουμε projects μαζί.",
    "forFounders.cta": "Pitch την ιδέα σου",
    "roster.badge": "Επιλεγμένα Έργα",
    "roster.title1": "Χτίζουμε",
    "roster.title2": "Ψηφιακή Υπεροχή.",
    "roster.subtitle1": "Όχι απλά projects. Πραγματικά builds.",
    "roster.subtitle2": "Μια επιλογή από case studies που αποδεικνύουν την ικανότητά μας να μετατρέπουμε το όραμα σε κερδοφόρα πραγματικότητα.",
    "growth.badge": "OPERATIONS & GROWTH",
    "growth.title1": "Scaling",
    "growth.title2": "Strategies",
    "growth.subtitle": "Ειδικά σχεδιασμένα μοντέλα συνεργασίας για projects που απαιτούν το απόλυτο στην υλοποίηση.",
    "growth.starter.name": "The Starter",
    "growth.starter.price": "από €1.8k",
    "growth.starter.desc": "Premium εταιρική παρουσία για επιχειρήσεις που αξίζουν μια κορυφαία ψηφιακή ταυτότητα.",
    "growth.scale.name": "The Scale",
    "growth.scale.price": "Custom",
    "growth.scale.desc": "Πλήρως αυτοματοποιημένα συστήματα, custom dashboards και μηχανές ανάπτυξης για μεγάλες επιχειρήσεις.",
    "growth.fractional.name": "The Fractional",
    "growth.fractional.price": "Μηνιαία",
    "growth.fractional.desc": "Ο δικός σου CTO και Creative Director ως υπηρεσία. Συνεχής ανάπτυξη και στρατηγική.",
    "growth.cta": "Request Access",
    "growth.badge_most_efficient": "Η πιο Αποδοτική",
    "space.badge": "Physical HQ",
    "space.title": "Hustle\nSpace",
    "space.text": "Ο premium υβριδικός μας χώρος στα Χανιά. Co-working, δικτύωση και πειραματισμός για ανήσυχα μυαλά.",
    "space.cta": "Επισκέψου το Space",
    "portfolio.hero.badge": "Το Αρχειο · Στρατηγικη · Υλοποιηση",
    "portfolio.hero.title1": "Πραγματικά Projects.",
    "portfolio.hero.title2": "Χτισμένα να αντέχουν.",
    "portfolio.hero.subtitle1": "Δεν φτιάχνουμε απλώς ιστοσελίδες.",
    "portfolio.hero.subtitle2": "Κατασκευάζουμε ψηφιακές μηχανές υψηλών επιδόσεων.",
    "portfolio.hero.explore": "Εξερεύνηση Έργων",
    "portfolio.hero.start": "Ξεκίνα Project",
    "portfolio.featured.badge": "Ισχυρός Αντίκτυπος",
    "portfolio.featured.title1": "Επιλεγμένα",
    "portfolio.featured.title2": "Έργα.",
    "portfolio.featured.subtitle": "Case studies που αποδεικνύουν την απόδοση (ROI).",
    "portfolio.archive.badge": "Το Αρχείο",
    "portfolio.archive.title1": "Όλα τα",
    "portfolio.archive.title2": "Έργα.",
    "portfolio.archive.empty": "Δεν βρέθηκαν έργα σε αυτήν την κατηγορία.",
    "portfolio.cta.badge": "THE EXECUTION PARTNER",
    "portfolio.cta.title1": "Χτίζουμε το",
    "portfolio.cta.title2": "Μέλλον.",
    "portfolio.cta.subtitle": "Στρατηγική και υλοποίηση για brands που απαιτούν το απόλυτο.",
    "portfolio.cta.button": "Ξεκίνα το Project",
    "portfolio.investments.badge": "Επενδυτικός Βραχίονας",
    "portfolio.investments.title": "Hustle Backed Projects",
    "portfolio.investments.subtitle": "Projects και ιδέες τρίτων στις οποίες η Hustle επενδύει κεφάλαιο, τεχνολογία και στρατηγική καθοδήγηση.",
    "footer.rights": "Με την επιφύλαξη παντός δικαιώματος.",
    "ecosystem.hero.badge": "The Infinite Ecosystem",
    "ecosystem.hero.title1": "Όλα όσα χρειάζεσαι",
    "ecosystem.hero.title2": "για να χτίσεις και να αναπτυχθείς.",
    "ecosystem.hero.subtitle": "Από επαγγελματικές υπηρεσίες μέχρι στρατηγική υποστήριξη. Δημιουργήσαμε ένα οικοσύστημα για την επόμενη γενιά των builders.",
    "ecosystem.hero.cta1": "Ξεκίνα το Ταξίδι σου",
    "ecosystem.hero.cta2": "Ξεκίνα ένα Project",
    "ecosystem.structure.badge": "Δομή",
    "ecosystem.structure.title1": "Χτίζουμε.",
    "ecosystem.structure.title2": "Υποστηρίζουμε.",
    "ecosystem.structure.title3": "Αναπτυσσόμαστε μαζί.",
    "ecosystem.structure.text": "Το HustleLabs είναι μια υβριδική μηχανή. Συνδυάζουμε την εκτελεστική ισχύ ενός digital agency με το στρατηγικό όραμα ενός startup studio.",
    "ecosystem.structure.agency.title": "The Agency (Build for you)",
    "ecosystem.structure.agency.desc": "Υψηλών επιδόσεων τεχνολογίες, marketing και συστήματα ανάπτυξης για επιχειρήσεις.",
    "ecosystem.structure.studio.title": "The Studio (Build with you)",
    "ecosystem.structure.studio.desc": "Στρατηγική υποστήριξη, ανάπτυξη προϊόντων και συνεργασίες βασισμένες σε equity.",
    "ecosystem.universe.badge": "ΣΥΣΤΑΤΙΚΑ",
    "ecosystem.universe.title": "The Lab Universe.",
    "ecosystem.universe.academy.title": "Hustle Academy",
    "ecosystem.universe.academy.desc": "Εκεί όπου φοιτητές και founders βρίσκουν την πραγματική γνώση για να χτίσουν επιχειρήσεις χωρίς περιττές θεωρίες.",
    "ecosystem.universe.space.title": "Hustle Space",
    "ecosystem.universe.space.desc": "Ο premium υβριδικός μας χώρος στα Χανιά. Co-working, δικτύωση και πειραματισμός για ανήσυχα μυαλά.",
    "ecosystem.universe.studio.title": "Hustle Studio",
    "ecosystem.universe.studio.desc": "Επαγγελματικά podcasts, vidcasts και εξοπλισμός δημιουργίας περιεχομένου για οραματιστές που θέλουν να ακουστούν.",
    "ecosystem.universe.network.title": "Hustle Network",
    "ecosystem.universe.network.desc": "Ένα επιλεγμένο οικοσύστημα από founders, δημιουργούς και ειδικούς που υποστηρίζουν ο ένας τον άλλον και χτίζουν μαζί.",
    "ecosystem.universe.explore": "Εξερεύνησε το",
    "ecosystem.universe.soon": "Σύντομα Κοντά σας",
    "ecosystem.network.badge": "Δίκτυο",
    "ecosystem.network.title": "Το σπίτι των",
    "ecosystem.network.title_span": "ανήσυχων ιδεών.",
    "ecosystem.network.text": "Επιλέγουμε έργα που αξίζει να χτιστούν. Από startups υψηλής ανάπτυξης μέχρι εδραιωμένες επιχειρήσεις που κυριαρχούν ψηφιακά.",
    "ecosystem.network.cta": "Εξερεύνησε το Δίκτυο",
    "ecosystem.manifesto.title": "Το σπίτι κάθε",
    "ecosystem.manifesto.title_span": "ανήσυχου μυαλού.",
    "ecosystem.manifesto.text": "Από τον φοιτητή που κάνει το πρώτο βήμα μέχρι τον ονειροπόλο που θέλει απλώς έναν χώρο για να πειραματιστεί και να χτίσει το μέλλον.",
    "ecosystem.final.badge": "Εξέλιξη",
    "ecosystem.final.title1": "Χτίσε το",
    "ecosystem.final.title2": "Μέλλον.",
    "ecosystem.final.cta1": "Ξεκίνημα Τώρα",
    "ecosystem.final.cta2": "Discovery Call",
    "ecosystem.final.quote": "\"Αν είσαι έτοιμος να εξελιχθείς, είμαστε εδώ.\"",
    "header.tooltip.project": "Ελάτε να χτίσουμε κάτι που λειτουργεί",
    "header.tooltip.space": "Δούλεψε από τον χώρο μας για μια μέρα",
    "tech.badge": "Το Τεχνολογικό Stack",
    "execution.badge": "Επίπεδο Υλοποίησης",
    "execution.title1": "Σκληρό Engineering.",
    "execution.title2": "Μαθηματική Ανάπτυξη.",
    "execution.step1.label": "Επικύρωση Concept",
    "execution.step1.desc": "Δεν χτίζουμε αν δεν βρούμε το κενό στην αγορά. Η στρατηγική είναι η πρώτη γραμμή κώδικα.",
    "execution.step2.label": "Αρχιτεκτονική Συστημάτων",
    "execution.step2.desc": "Next-gen κατασκευές με μηδενική συντήρηση. Επεκτάσιμες, ασφαλείς και ταχύτατες.",
    "execution.step3.label": "Επιθετική Ανάπτυξη",
    "execution.step3.desc": "Μετάβαση από ένα προϊόν σε ηγέτη της αγοράς μέσω αυτοματοποιημένων συστημάτων ανάπτυξης.",
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("hustle_lang");
    return (saved as Language) || "gr";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("hustle_lang", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};
